const sections = [
  {
    number: '01',
    title: 'Acceptance of Terms',
    body: 'By accessing or using AI Creative Strategist, you agree to comply with and be bound by these Terms and Conditions. If you do not agree with any part of these terms, please discontinue use of the platform.',
  },
  {
    number: '02',
    title: 'Service Description',
    body: 'AI Creative Strategist provides AI-generated brand strategy recommendations, audience insights, creative narratives, visual direction suggestions, and marketing prompt generation based on user-provided information. The platform is intended for informational, educational, and creative assistance purposes only.',
  },
  {
    number: '03',
    title: 'AI-Generated Content',
    body: 'All outputs generated by the platform are created using artificial intelligence and should be treated as recommendations rather than professional business, legal, financial, or marketing advice. Users are responsible for independently reviewing, validating, and adapting generated content before implementing it in real-world projects.',
  },
  {
    number: '04',
    title: 'User Responsibility',
    body: 'Users agree not to submit unlawful, harmful, misleading, defamatory, or infringing content through the platform. Users remain fully responsible for any decisions, actions, campaigns, branding initiatives, or business outcomes resulting from the use of generated content.',
  },
  {
    number: '05',
    title: 'Intellectual Property',
    body: 'Users retain ownership of the information they provide to the platform. Generated outputs may be used, modified, published, or incorporated into personal or commercial projects by the user. The platform\'s source code, design, branding, and underlying implementation remain the property of the creator unless otherwise stated.',
  },
  {
    number: '06',
    title: 'Limitation of Liability',
    body: 'AI Creative Strategist is provided "as is" without warranties of any kind. The platform and its creator shall not be held liable for any direct, indirect, incidental, consequential, or business-related losses arising from the use of generated content or recommendations.',
  },
  {
    number: '07',
    title: 'Availability',
    body: 'We reserve the right to modify, suspend, or discontinue any feature of the platform at any time without prior notice.',
  },
  {
    number: '08',
    title: 'Privacy',
    body: 'Information submitted through the platform is used solely for generating requested outputs. Users should avoid submitting sensitive personal, confidential, or proprietary information.',
  },
  {
    number: '09',
    title: 'Changes to Terms',
    body: 'These Terms and Conditions may be updated periodically. Continued use of the platform after updates constitutes acceptance of the revised terms.',
  },
  {
    number: '10',
    title: 'Contact',
    body: 'For questions, feedback, or inquiries regarding these Terms and Conditions, users may contact the creator through the links provided within the platform.',
  },
]

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#F9F8F6] pt-14">
      <div className="max-w-3xl mx-auto px-6 py-20 space-y-12">

        {/* Header */}
        <div className="space-y-4 pb-10 border-b border-gray-100">
          <p className="text-xs text-gray-300 tracking-widest uppercase font-medium">Legal</p>
          <h1 className="text-4xl font-bold text-gray-900">Terms & Conditions</h1>
          <p className="text-sm text-gray-400">Last Updated: June 2026</p>
        </div>

        {/* Intro */}
        <p className="text-sm text-gray-500 leading-relaxed">
          Please read these Terms and Conditions carefully before using AI Creative Strategist.
          By using the platform, you acknowledge that you have read, understood, and agreed to
          be bound by these terms.
        </p>

        {/* Sections */}
        <div className="space-y-6">
          {sections.map(s => (
            <div key={s.number} className="bg-white border border-gray-100 rounded-2xl p-6 shadow-sm space-y-2">
              <div className="flex items-center gap-3">
                <span className="text-xs font-semibold text-gray-300 tracking-widest">{s.number}</span>
                <p className="text-sm font-semibold text-gray-700 uppercase tracking-wide">{s.title}</p>
              </div>
              <p className="text-sm text-gray-500 leading-relaxed">{s.body}</p>
            </div>
          ))}
        </div>

        {/* Footer note */}
        <div className="pt-4 border-t border-gray-100">
          <p className="text-xs text-gray-300 italic">
            By using AI Creative Strategist, you acknowledge that you have read, understood, and
            agreed to these Terms and Conditions.
          </p>
        </div>
      </div>
    </div>
  )
}//built by kshitisha